### ISSUE TITLE
Is @extends support working properly?

### ISSUE THREAD

**Issue by whitlockjc** [otris/jsdoc-tsd#56] opened 2019-05-17 01:45 UTC
Whenever I use `class B extends A` in JavaScript, with the appropriate `@extends` tag, instead of the TSD containing `class B extends A`, I end up with all members of `A` being duplicated in `B`.  Is this the desired approach?

**Comment by wehrstedt** [comment] 2019-08-09 22:54
I was able to reproduce this. No, its not the desired approach. I added a test on my branch to reproduce this temporay (see [here](https://github.com/wehrstedt/jsdoc-tsd/commit/68d6773689c91e4549cb808fd9eba694e7de5c9a)).

**Comment by MichalCz** [comment] 2019-08-12 10:56
@wehrstedt it seems now working in `scramjet`... I'll try to remove some of my overrides.

**Comment by MichalCz** [comment] 2019-08-12 11:42
...and confirmed - `extends DataStream` are now nicely added without my awful hack. :)

**Comment by wehrstedt** [comment] 2019-08-12 17:25
@MichalCz No duplicated members?

**Comment by MichalCz** [comment] 2019-08-12 17:27
I need to check if I don't have any counter measures for this. I'll get back to you in a couple minutes.

**Comment by MichalCz** [comment] 2019-08-12 17:54
Yup. I managed to remove this much of my hacks: [see commit](https://github.com/signicode/scramjet/commit/7ce774e6491888e20958fc4c06e1a2ee374834e6).

Seems to work well and doesn't add the augmented methods.

**Comment by wehrstedt** [comment] 2019-08-13 21:26
Strange, because I can repruduce this error with a simple example as shown [here] (https://github.com/wehrstedt/jsdoc-tsd/commit/68d6773689c91e4549cb808fd9eba694e7de5c9a)

**Comment by MichalCz** [comment] 2019-08-13 21:30
I may have some filtering in place in another part of my plugin.

I'll check tomorrow and report back.

**Comment by MichalCz** [comment] 2019-08-15 12:05
Oh, ok, now I noticed... Yes, I still have those extends replacements...

**Comment by MichalCz** [comment] 2019-08-15 22:36
So I was trying to get around the code and wrote a bit of code that would look up the right extends and set it. This would go around the same place where members are assigned to top-level objects, but the thing is that since `StringStream extends DataStream` and since `DataStream` is `@memberof module:scramjet` it can't look it up properly.

I'll set up a fork tomorrow and push my changes as work in progress. Maybe it'd make more sense to you - I sadly could continue no sooner than Monday evening.

**Comment by MichalCz** [comment] 2019-08-15 22:40
I pushed changes here: https://github.com/otris/jsdoc-tsd/compare/master...MichalCz:feature/class-extends?expand=1

**Comment by MichalCz** [comment] 2019-08-16 10:35
@wehrstedt I pushed a commit that resolves classes. Please take a look in the link above.

**Comment by wehrstedt** [comment] 2019-08-16 11:25
Can you have a look at this test case? https://github.com/wehrstedt/jsdoc-tsd/blob/issue/56/test/class/test.parseClass.ts#L161

Is this the setup in your project?

**Comment by MichalCz** [comment] 2019-08-16 11:30
It's a bit different: [StringStream is also `@memberof module:scramjet` and `extends DataStream`](https://github.com/wehrstedt/jsdoc-tsd/blob/issue/56/test/class/test.parseClass.ts#L185).

Best seen here in [NumberStream extends DataStream](https://github.com/signicode/scramjet/blob/master/lib/number-stream.js#L8)

**Comment by wehrstedt** [comment] 2019-08-16 21:00
@MichalCz I found the issue.

1. I fixed the duplication of members and classes 34f970de04bf7a24687d099ec670abd53e02fa45 and cc997ac0db72d5ddccd44ee02d7164fc39c90d9c (the second issue only occurres in tests because of calling `resolveMembership` multiple times).
2. I cherry-picked your changes because after my fixes there were some merge conflicts.
3. The issue that classes of modules currently can't be resolved is because of the naming schema of jsdoc. Take a look at the test I added with 2a1a95bbda9e810f5545014c9c93b56003709b63. The extends relation is written as `module:scramjet~DataStream` (note the **~**). The longname of this item is `module:scramjet.DataStream` (now it's written with a dot). 
The [comparison](https://github.com/wehrstedt/jsdoc-tsd/blob/2a1a95bbda9e810f5545014c9c93b56003709b63/src/core/jsdoc-tsd-parser.ts#L254) will not succeed because you are comparing the `~` version with the dotted version.
 
Addtionally the [comparison](https://github.com/wehrstedt/jsdoc-tsd/blob/2a1a95bbda9e810f5545014c9c93b56003709b63/src/core/jsdoc-tsd-parser.ts#L255) will not become true because `cls.original.name` equals the name of the class (not the longname) and `augments` equals the longname of the class.

You can easily debug this by starting [this test](https://github.com/wehrstedt/jsdoc-tsd/blob/2a1a95bbda9e810f5545014c9c93b56003709b63/test/module/test.parseModule.ts#L125)

**Comment by wehrstedt** [comment] 2019-08-18 14:12
I forgot to mention that your changes for extending classes works, good job. I also added a test with 4a58cde526e9ffb1059b31e17851c840ad9c0d79 for that, thank you.

**Comment by MichalCz** [comment] 2019-08-18 15:20
Cool and no probs. :)

**Comment by wehrstedt** [comment] 2019-08-30 07:22
> So I was trying to get around the code and wrote a bit of code that would look up the right extends and set it. This would go around the same place where members are assigned to top-level objects, but the thing is that since `StringStream extends DataStream` and since `DataStream` is `@memberof module:scramjet` it can't look it up properly.
> 
> I'll set up a fork tomorrow and push my changes as work in progress. Maybe it'd make more sense to you - I sadly could continue no sooner than Monday evening.

@MichalCz Do you want to fix the lookup for modules? Its the only missing part to finish this PR.

**Comment by MichalCz** [comment] 2019-08-30 07:26
Im sorry, but I have so much extra work that I can't reliably commit to any time spent there. I'll create a separate PR for this later

**Comment by wehrstedt** [comment] 2019-09-16 11:12
@MichalCz I applied the changes you and I have already done with #74. I will create a separate issue for the support of module members

**Closed by wehrstedt** 2019-09-16 11:12 UTC
Labels: help wanted
